version: '3.8'

services:
  # Aplicação completa (Frontend + Backend)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "8080:8080"  
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/iotcity
      - SPRING_DATASOURCE_USERNAME=iotcity_user
      - SPRING_DATASOURCE_PASSWORD=iotcity_pass
    depends_on:
      - db
    networks:
      - iot-city-network
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=iotcity
      - POSTGRES_USER=iotcity_user
      - POSTGRES_PASSWORD=iotcity_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - iot-city-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iotcity_user -d iotcity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  iot-city-network:
    driver: bridge 